include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/api/models/*.g.dart

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false