name: Analyze

on:
  workflow_call:

jobs:
  analyze:
    name: Analyze and lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Cache Flutter modules
        uses: actions/cache@v3
        env:
          cache-number: ${{ secrets.CACHE_NUMBER }}
        with:
          path: |
            ~/.pub-cache/bin
          key: ${{ runner.os }}-pub-${{ env.cache-number }}-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-${{ env.flutter_version }}-
            ${{ runner.os }}-pub-
            ${{ runner.os }}-
      - name: No analytics
        run: dart --disable-analytics && flutter config --no-analytics # =)
      - name: Install packages
        run: flutter pub get
      - name: Codegen
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Linter
        run: flutter analyze --no-fatal-warnings --no-fatal-infos
      - name: Analyze Flutter
        uses: ValentinVignal/action-dart-analyze@v0.14
        with:
          emojis: 'false'
      - name: Verify formatting
        run: dart format --set-exit-if-changed .
