name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

env:
  DOCKER_HUB: acetylsalicylicacid/${{ github.event.repository.name }}

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  build_android:
    name: Build android
    needs: lint
    runs-on: macos-latest
    steps:
      - run: flutter build apk
      - run: flutter build appbundle
  build_ios:
    name: Build iOS
    needs: lint
    runs-on: macos-latest
    steps:
      - run: flutter build ios --release --no-codesign