name: Build iOS

on:
  workflow_call:

jobs:
  build_ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
      - name: Disable analytics
        run: dart --disable-analytics && flutter config --no-analytics
      - name: Install packages
        run: flutter pub get
      - name: Codegen
        run: flutter packages pub run build_runner build
      - name: Generate icons and splash
        run: flutter pub run flutter_launcher_icons:main && flutter pub run flutter_native_splash:create
      - name: Build
        run: flutter build ios --release --no-codesign
