name: Build Android

on:
  workflow_call:

jobs:
  build_android:
    name: Build android
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Cache Gradle modules
        uses: actions/cache@v2.1.6
        env:
          cache-number: ${{ secrets.CACHE_NUMBER }}
        with:
          path: |
            ~/android/.gradle
            ~/.gradle/cache
            # ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ env.cache-number }}-${{ hashFiles('android/build.gradle') }}-${{ hashFiles('android/app/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ env.cache-name }}-${{ hashFiles('android/build.gradle') }}
            ${{ runner.os }}-gradle-${{ env.cache-name }}-
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-
      - name: Cache Flutter modules
        uses: actions/cache@v2.1.6
        env:
          cache-number: ${{ secrets.CACHE_NUMBER }}
        with:
          path: |
            ~/.pub-cache/bin
          key: ${{ runner.os }}-pub-${{ env.cache-number }}-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-${{ env.flutter_version }}-
            ${{ runner.os }}-pub-
            ${{ runner.os }}-
      - run: dart --disable-analytics && flutter config --no-analytics # =)
      - run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter pub run flutter_launcher_icons:main && flutter pub run flutter_native_splash:create
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            build/app/outputs/apk/release/app-release.apk
