name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

env:
  DOCKER_HUB: acetylsalicylicacid/${{ github.event.repository.name }}

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  build_android:
    name: Build android
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter packages pub run build_runner build
      - run: flutter build apk
      - run: flutter build appbundle
  build_ios:
    name: Build iOS
    needs: lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter packages pub run build_runner build
      - run: flutter build ios --release --no-codesign