name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '*.md'

jobs:
  analyze:
    uses: ./.github/workflows/analyze.yml
  pana:
    needs: analyze
    uses: ./.github/workflows/pana.yml
  build_android:
    needs: pana
    uses: ./.github/workflows/build-android.yml
  build_ios:
    needs: pana
    uses: ./.github/workflows/build-ios.yml
