name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  analyze:
    uses: ./.github/workflows/analyze.yml
  build_android:
    needs: analyze
    uses: ./.github/workflows/build-android.yml
  build_ios:
    needs: analyze
    uses: ./.github/workflows/build-ios.yml
